awsRegion: 'us-east-1'
mongoDBHost: 10.0.1.9
mongoDBName: 'universal-sales'
mongoDBPassword: null
mongoDBPort: 27017
mongoDBReplset: null
mongoDBUsername: null
s3Bucket: ''
ssmPath: 'pf-appsync-demo'
nodeEnv: 'prod'
usessm: true