awsRegion: 'ca-central-1'
mongoDBHost: 10.0.1.9
mongoDBName: 'universal-sales'
mongoDBPassword: null
mongoDBPort: 27017
mongoDBReplset: null
mongoDBUsername: null
s3Bucket: ''
ssmPath: 'rn-test'
nodeEnv: 'prod'
usessm: true